### ISSUE TITLE
No focus or High light on Option Selection

### ISSUE THREAD

**Issue by EdwinOkoronkwo** [markthomasmiller/sorcerer#1]
When you right-click on the screen/page and attempt to select an action such as copy, cut, paste, refactor etc, there is no indication or focus on the action.  There should be some focus when we hover on options.

**Comment by markthomasmiller** [comment]
Thanks for pointing this out Edwin. I'm on a Mac, and it uses the system menu for right-clicking, so I never noticed this.

Does someone with access to a different OS want to look at a fix? You could probably use a hex code with some transparency, like `#ffffff22`, as the highlight/focus color.

**Comment by EdwinOkoronkwo** [comment]
Hi Mark, I really like the Sorcerer theme. Its probably the best dark theme on VS Code. Yes, I am on Windows and no one around me has a Mac. So the problem here is that the Context menu does not high-light and I do not know how to correct the problem on VS Code. I do not know how to add some transparency as you mention above. I tried to modify my settings.js file but I don't see where to make changes.

![contextmenu](https://user-images.githubusercontent.com/49468467/97209420-ef6c3c00-1781-11eb-8224-b744bb830ab8.PNG)

**Comment by rishisundar** [comment]
Hi @markthomasmiller ,
I have added fix for this issue as [PR](https://github.com/markthomasmiller/sorcerer/pull/7). Can you please assign this to me and review my changes?

**Comment by rishisundar** [comment]
@markthomasmiller Now that this issue is fixed in the latest release, I guess this issue can be closed. 

P.S I should've linked this issue with my PR to close this one automatically. Didn't know about the flow since this was my first PR. Sorry about that.
