### ISSUE TITLE
Imports color

### ISSUE THREAD

**Issue by seloner** [markthomasmiller/sorcerer#3]
Hello why are not my imports with grey color ?
![image](https://user-images.githubusercontent.com/29483115/102611233-3863bf80-4137-11eb-83ee-c2dc1a307be6.png)

**Comment by markthomasmiller** [comment]
I haven't seen this before; could I get your operating system, the active language (in the bottom right corner, pictured below), and a list of any extensions you have installed?

<img width="182" alt="Screen Shot 2020-12-18 at 9 19 33 AM" src="https://user-images.githubusercontent.com/34243743/102624545-26235a80-4112-11eb-89bb-12bbc2ca695e.png">

**Comment by seloner** [comment]
I am on windows and this extension was the issue https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel . When I removed it the issue was fixed .
