### ISSUE TITLE
Typescript support ?

### ISSUE THREAD

**Issue by seloner** [markthomasmiller/sorcerer#4]
Is it possible to get the same syntax styles like white imports for typescript files ?

**Comment by seloner** [comment]
Merge pleasse:D

**Comment by markthomasmiller** [comment]
Hey @seloner, #5 was merged! It should be live on the VSCode marketplace soon.

It sounds like there will be an additional PR that improves the font weights as well.

Thanks for using Sorcerer! 😄

**Comment by seloner** [comment]
Nice !!!
